=== Noitham/SchoolXQJ/build/classes/schoolxqj/xml/school.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="studentref" type="xs:string"/>
  <xs:element name="coursename" type="xs:string"/>
  <xs:element name="duration" type="xs:integer"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="enrolled">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="studentref" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="course">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="coursename" minOccurs="0"/>
        <xs:element ref="duration" minOccurs="0"/>
        <xs:element ref="description" minOccurs="0"/>
        <xs:element ref="enrolled" minOccurs="0"/>
        <xs:element ref="courseref" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="courseref" type="xs:string"/>
  <xs:element name="studentname" type="xs:string"/>
  <xs:element name="age" type="xs:integer"/>
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="studentname"/>
        <xs:element ref="age"/>
        <xs:element ref="course"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="courses">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="course" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="student" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="school">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="courses"/>
        <xs:element ref="students"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Noitham/SchoolXQJ/build/classes/schoolxqj/xml/school.xml
<school xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="school.xsd">
    <courses>
        <course id="M03">
            <coursename>Programacio</coursename>
            <duration>198</duration>
            <description>M03 - Programacio</description>
            <enrolled>
                <studentref>a1</studentref>
                <studentref>a2</studentref>
                <studentref>a3</studentref>
            </enrolled>
        </course>
        <course id="M06">
            <coursename>Acces a dades</coursename>
            <duration>99</duration>
            <description>M06 - Acces a dades</description>
            <enrolled>
                <studentref>a1</studentref>
                <studentref>a2</studentref>
                <studentref>a3</studentref>
            </enrolled>
        </course>
        <course id="M08">
            <coursename>Programacio multimedia Apps Mobils</coursename>
            <duration>99</duration>
            <description>M08 - Programacio multimedia Apps Mobils</description>
            <enrolled>
                <studentref>a4</studentref>
            </enrolled>
        </course>
        <course id="M10">
            <coursename>Sistemes de gestio empresarial</coursename>
            <duration>99</duration>
            <description>M10 - Sistemes de gestio empresarial</description>
            <enrolled>
            </enrolled>
        </course>
    </courses>
    <students>
        <student id="a1">
            <studentname>David</studentname>
            <age>17</age>
            <course>
                <courseref>M03</courseref>
                <courseref>M06</courseref>
            </course>
        </student>
        <student id="a2">
            <studentname>Josep</studentname>
            <age>20</age>
            <course>
                <courseref>M03</courseref>
                <courseref>M06</courseref>
            </course>
        </student>
        <student id="a3">
            <studentname>Guillermo</studentname>
            <age>22</age>
            <course>
                <courseref>M03</courseref>
                <courseref>M06</courseref>
            </course>
        </student>
        <student id="a4">
            <studentname>Ramon</studentname>
            <age>25</age>
            <course>
                <courseref>M08</courseref>
            </course>
        </student>
        <student id="a5">
            <studentname>Dani</studentname>
            <age>27</age>
            <course>
            </course>
        </student>
    </students>
</school>
